version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: libyacv
    container_name: libyacv-app
    restart: unless-stopped
    working_dir: /var/www/html/
    ports:
      - 8089:80
    volumes:
      - ./:/var/www/html
