name: Deployment Workflow
on: 
  push:
    branches: [ master ]


jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: libyacv.com
        username: root
        key: ${{ secrets.LIBYACV_SECRET }}
        port: 22
        script: |
          cd /var/www/laravel
          git pull origin master
          git status
